/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package database;

import java.sql.*;
public class App {

    public void TestOne() {
        String url="jdbc:mysql://98.166.255.71:3306/proximity_connect";
        String username="YellowTeam";
        String password="Yellow411w";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection connection = DriverManager.getConnection(url, username, password);
            Statement statement = connection.createStatement();
        ResultSet ResultSet=statement.executeQuery("select * from users");
            while(ResultSet.next()){
                System.out.println(ResultSet.getInt(1)+" "+ResultSet.getString(2)+" "+ResultSet.getString(3)+" "+ResultSet.getString(4)+" ");
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
}
