/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package database;

import java.sql.*;
public class DatabaseQueries {
    Connection PCDatabase;
    /*
     * Constructs the class and connects to the database
     */
    public DatabaseQueries(){
        String url="jdbc:mysql://98.166.255.71:3306/proximity_connect";
        String username="YellowTeam";
        String password="Yellow411w";
        try{
            PCDatabase = DriverManager.getConnection(url, username, password);
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    /*
     * Fills database with sample data
     */
    public void fillSampleData(){
        String userNames[] = {"Sean", "Charles", "Jon","William","Khama","Brianna"};
        String password[] = {"1234", "TestPassword", "SomethingSecure", "Pass1234", "Pineapple", "Oranges"};
        String datecreated[] = {"2024-01-25", "2019-02-11", "1980-05-14", "1999-12-31", "2001-09-25", "2022-04-09"};
        String color[]={"(255, 0, 255)","(90, 200, 98)","(133, 125, 60)","(30, 170, 99)","(90, 255, 125)","(0, 255, 255)",};
        String UIFont[]={"Times New Roman", "Comic Sans", "Calibri", "Bell MT", "Gill Sans MT", "Gradl"};
        String PL[]={"English", "English", "Spanish", "German", "English", "English"};
        String LN[]={"Fulbright", "Milroy", "Rossy", "Glavin", "Jeffrey", "Spigner"};
        for(int i =0;i<6;i++){
            int UID = getNextUserID();
            AddUser(UID, userNames[i], password[i], datecreated[i]);
            updateUserSettings(UID, color[i], UIFont[i], userNames[i], LN[i], PL[i]);
        }
        CreateGroup(nextGroupID(), "Pineapples", 1);
        CreateGroup(nextGroupID(), "TestGroup", 3);
    }
    /*
     * Adds a new user for to the data base
     * 
     */
    public void AddUser(int id, String name, String password, String Date){
        try{
            PCDatabase.createStatement().execute("insert into users (user_id, username, user_password, created_at) values("+id+", \'"+name+"\', \'"+password+"\', \'"+Date+"\')");
        }
        catch (Exception e){
            System.out.println("AddUser Error:\n    "+e);
        }
        defaultSettings(id);
    }
    /*
     * Gets the next available ID for a User 
     */
    public int getNextUserID(){
        try{
            ResultSet results = PCDatabase.createStatement().executeQuery("select max(user_id) from users");
            if(results.next())
                return results.getInt(1) + 1;
            else
                return 1;
        }
        catch (Exception e){
            System.out.println("GetNextUserID Error:\n    "+e);
        }
        return -1;
    }
    public int Login(int userID, String password){
        try{
            ResultSet results = PCDatabase.createStatement().executeQuery("select user_id from users where user_id="+userID+" and user_password=\'"+password+"\'");
            if(results.next())
                return results.getInt("user_id");
        }
        catch (Exception e){
            System.out.println("GetNextID Error:\n    "+e);
        }
        return -1;
    }
    public void updatePassword(int user_id, String oldPassword, String newpassword){
        try{
            PCDatabase.createStatement().execute("update users set user_password=\'"+newpassword+"\' where user_id="+user_id+" and user_password=\'"+oldPassword+"\'");
        }
        catch (Exception e){
            System.out.println("updatePassword Error:\n    "+e);
        }
    }
    public void defaultSettings(int UID){
        try{
            PCDatabase.createStatement().execute("insert into user_settings (user_id, UI_color, UI_Font, first_name, last_name, primary_language) values ("+UID+", \'(255, 255, 255)\', \'Times New Roman\', \'FirstName\', \'LastName\',\'English\')");
        }
        catch (Exception e){
            System.out.println("defaultSettings Error:\n    "+e);
        }
    }
    public void updateUserSettings(int UID, String color, String Font, String Fname, String LName, String primary_language){
        try{
            PCDatabase.createStatement().execute("update user_settings set UI_color=\'"+color+"\', UI_Font=\'"+Font+"\', first_name=\'"+Fname+"\', last_name=\'"+LName+"\', primary_language=\'"+primary_language+"\' where user_id="+UID+"");
        }
        catch (Exception e){
            System.out.println("updateUserSettings Error:\n    "+e);
        }
    }
    public int nextGroupID(){
        try{
            ResultSet results = PCDatabase.createStatement().executeQuery("select max(group_id) from user_group");
            if(results.next())
                return results.getInt(1) + 1;
            else
                return 1;
        }
        catch (Exception e){
            System.out.println("GetNextGroupID Error:\n    "+e);
        }
        return -1;
    }
    public void CreateGroup(int groupID, String name, int creatorID){
        try{
            PCDatabase.createStatement().execute("insert into user_group (group_id, group_name, group_creator) values ("+groupID+", \'"+name+"\', "+creatorID+")");
            PCDatabase.createStatement().execute("insert into group_members (group_id, user_id) values ("+groupID+", "+creatorID+")");
        }
        catch (Exception e){
            System.out.println("CreateGroup Error:\n    "+e);
        }
    }
    public void addGroupMember(int groupID, int userID){
        try{
            PCDatabase.createStatement().execute("insert into group_members (user_id, group_id) values ("+userID+", "+groupID+")");
        }
        catch (Exception e){
            System.out.println("CreateGroup Error:\n    "+e);
        }
    }
    public int[] getGroups(int user_id){
        try{
            ResultSet len = PCDatabase.createStatement().executeQuery("select count(group_id) from group_members where user_id="+user_id);
            int group_values[];
            if(len.next()){
                group_values = new int[len.getInt(1)];
            }
            else{
                return null;
            }
            ResultSet groups = PCDatabase.createStatement().executeQuery("select group_id from group_members where user_id="+user_id);
            int i =0;
            while(groups.next()){
                group_values[i]=groups.getInt("group_id");
                i++;
            }
            return group_values;
        }
        catch(Exception e){
            System.out.println("getGroups Error:\n    "+e);
        }
        return null;
    }
    public int[] getGroupMembers(int group_id){
        try{
            ResultSet len = PCDatabase.createStatement().executeQuery("select count(user_id) from group_members where group_id="+group_id);
            int members[];
            if(len.next()){
                members = new int[len.getInt(1)];
            }
            else{
                return null;
            }
            ResultSet Members = PCDatabase.createStatement().executeQuery("select user_id from group_members where group_id="+group_id);
            int i =0;
            while(Members.next()){
                members[i]=Members.getInt("user_id");
                i++;
            }
            return members;
        }
        catch(Exception e){
            System.out.println("getGroupMembers Error:\n    "+e);
        }
        return null;
    }
    public int getNextMeetingID(){
        try{
            ResultSet results = PCDatabase.createStatement().executeQuery("select max(meeting_id) from group_meetings");
            if(results.next())
                return results.getInt(1) + 1;
            else
                return 1;
        }
        catch(Exception e){
            System.out.println("getNextMeetingID Error:\n    "+e);
        }
        return -1;
    }
    public void CreateMeeting(int meeting_id, int group_id, String meeting_name, String dateTime, boolean shareable){
        try{
            PCDatabase.createStatement().execute("insert into group_meetings (group_id, meeting_id, meeting_name, meeting_date, shareable) values ("+group_id+", "+meeting_id+", \'"+meeting_name+"\', \'"+dateTime+"\', "+shareable+")");
        }
        catch(Exception e){
            System.out.println("CreateMeeting Error:\n    "+e);
        }
    }
    public int[] getGroupMeetings(int group_id){
        try{
            ResultSet len = PCDatabase.createStatement().executeQuery("select count(meeting_id) from group_meetings where group_id="+group_id);
            int meetings[];
            if(len.next()){
                meetings = new int[len.getInt(1)];
            }
            else{
                return null;
            }
            ResultSet Meetings = PCDatabase.createStatement().executeQuery("select meeting_id from group_meetings where group_id="+group_id);
            int i =0;
            while(Meetings.next()){
                meetings[i]=Meetings.getInt("meeting_id");
                i++;
            }
            return meetings;
        }
        catch(Exception e){
            System.out.println("getGroupMembers Error:\n    "+e);
        }
        return null;

    }
    public int getNextMessageID(int meeting_id){
        try{
            ResultSet results = PCDatabase.createStatement().executeQuery("select max(message_id) from messages where meeting_id="+meeting_id);
            if(results.next())
                return results.getInt(1) + 1;
            else
                return 1;
        }
        catch(Exception e){
            System.out.println("getNextMessageID Error:\n    "+e);
        }
        return -1;
    }
    public void createMessage(int user_id, int meeting_id, int message_id, String message, String dateTime, boolean pinned){
        try{
            PCDatabase.createStatement().execute("insert into messages (user_id, meeting_id, message_id, body, created_at, pinned) values ("+user_id+", "+meeting_id+", "+message_id+", \'"+message+"\', \'"+dateTime+"\', "+pinned+")");
        }
        catch(Exception e){
            System.out.println("CreateMessage Error:\n    "+e);
        }
    }
}
